# Stage 1: Build stage
FROM node:latest AS build

WORKDIR /app/lnt-frontend

COPY package*.json ./

RUN npm install

COPY . .


RUN npm run build

# Stage 2: Production stage
FROM node:alpine

WORKDIR /app


RUN npm install -g http-server


COPY --from=build /app/lnt-frontend/dist /app/build

EXPOSE 8081

CMD ["http-server", "-p", "8081", "./build"]